### ISSUE TITLE
Image Processing Class

### ISSUE THREAD

**Issue by HLRobotics** [HLRobotics/UGV#2]
Create a new branch from the  main and let us try to work on the following task.
Let me know on which task u guys are working . Happy Coding

- [x] 1. Open Webcam via IP v4 address using python 
- [ ] 2. Human Detection via cam python
- [x] 3. Motion Detection via cam python
- [ ] 4. Obstacle Detection via cam python

**Comment by HLRobotics** [comment]
Guys let me know in which task you are working on.

**Comment by jimo910** [comment]
Working on it already

**Comment by HLRobotics** [comment]
noted
